### ISSUE TITLE
Schematics?

### ISSUE THREAD

**Issue by janusdn** [skarlsso/IRRemoteIVT#1]
Hi,

Do you have any schematics, pictures or textual description available for this project. I would like to build a similar project. Anything you could share would make it easier for me. 

Thanks.

**Comment by skarlsso** [comment]
Hi Janus,

Unfortunately, I don't have a schematic, since I thought the solution was too crude. I'm simply using a transistor as a switch, just like what's described on, for example:
http://wiki.analog.com/university/courses/eps/bjt-switch

I'm going to change the circuit (when I get access to the heat pump again) to use a constant current led driver instead. When that has been done and I've tested that it works, I'll make sure to upload a schematic. 

A tip, if you do set this up make sure to have the diode(s) pointing straight towards the receiver, as the IR beams are usually very narrow.

Good luck!

**Comment by janusdn** [comment]
Hi!

Thanks for your quick reply I will look into your link and see if can make it work. This will be a project which stretches over some time as the heat pump is in a vacation house.

I will look forward to hear about your findings on the usage of the constant current led driver.

**Comment by skarlsso** [comment]
I've had almost no access to the heat pump this year, so I'll probably not be doing anything with this code for some time. :(

**Comment by janusdn** [comment]
Thank you for the update. I have also had way to much to do. But the project is still on my todo list :)

**Comment by skarlsso** [comment]
I've added a schematic to show how I've connected the IR LED to the Arduino:
https://github.com/skarlsso/IRRemoteIVT/blob/master/schematics/kicad/IRRemoteIVT-schematic.png

I've also updated the description with part numbers and restructured the code.

**Comment by janusdn** [comment]
Excellent. Thanks.
